# This file is now secondary to flake.nix if using devenv,
# but can be kept for environments not using nix.
# To ensure parity, hooks here should also use local just calls.

repos:
  - repo: local
    hooks:
      - id: just-lint
        name: just-lint
        entry: just lint
        language: system
        files: \.go$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
