name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Lint
        run: nix develop --command just lint

      - name: Build
        run: nix develop --command just build

      - name: Test
        run: nix develop --command just test
